import { NextResponse } from 'next/server';

export async function GET() {
  const data = [
    {
      id: 1,
      name: "Rock Garden",
      description: "A sculpture garden created by Nek Chand.",
      image: "/tourism/rock.png",
      lat: 30.7526,
      lon: 76.8104,
      address: "Sector 1, Chandigarh",
      category: "Art",
    },
    {
      id: 2,
      name: "Sukhna Lake",
      description: "A beautiful man-made lake at the foothills.",
      image: "/tourism/lake.png",
      lat: 30.7415,
      lon: 76.8188,
      address: "Sector 1, Chandigarh",
      category: "Nature",
    },
    {
      id: 3,
      name: "Rose Garden",
      description: "One of Asia’s largest rose gardens.",
      image: "/tourism/rose.png",
      lat: 30.7412,
      lon: 76.7732,
      address: "Sector 16, Chandigarh",
      category: "Garden",
    },
    {
      id: 4,
      name: "Elante Mall",
      description: "Popular shopping and entertainment hub.",
      image: "/tourism/mall.png",
      lat: 30.7046,
      lon: 76.8026,
      address: "Industrial Area Phase I, Chandigarh",
      category: "Shopping",
    },
    {
      id: 5,
      name: "Pinjore Gardens",
      description: "Historic 17th-century Mughal-style garden.",
      image: "/tourism/1.png",
      lat: 30.8006,
      lon: 76.9189,
      address: "Pinjore, Panchkula",
      category: "Historic",
    },
    {
      id: 6,
      name: "Chandigarh Capitol Complex",
      description: "UNESCO World Heritage site designed by Le Corbusier.",
      image: "/tourism/2.png",
      lat: 30.7521,
      lon: 76.8028,
      address: "Sector 1, Chandigarh",
      category: "Architecture",
    },
    {
      id: 7,
      name: "Zakir Hussain Rose Garden",
      description: "Known for thousands of rose varieties.",
      image: "/tourism/3.png",
      lat: 30.7413,
      lon: 76.7731,
      address: "Sector 16, Chandigarh",
      category: "Park",
    },
    {
      id: 8,
      name: "Japanese Garden",
      description: "Japanese-themed garden with pagodas and bridges.",
      image: "/tourism/4.png",
      lat: 30.7192,
      lon: 76.7837,
      address: "Sector 31, Chandigarh",
      category: "Garden",
    },
    {
      id: 9,
      name: "Terraced Garden",
      description: "Garden with light shows and musical fountain.",
      image: "/tourism/5.png",
      lat: 30.7347,
      lon: 76.7726,
      address: "Sector 33B, Chandigarh",
      category: "Garden",
    },
  ];

  return NextResponse.json(data);
}
